# See https://wiki.libsdl.org/SDL_Keycode for key names

[general]
fastforward = "Space"
reset = "F9"
fullscreen = "F10"

[gba]
a = "A"
b = "S"
l = "D"
r = "F"
start = "Return"
select = "Backspace"
up = "Up"
down = "Down"
left = "Left"
right = "Right"
