#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2020-present Fewtarius

###
### A simple loop to watch the status of any active builds.
###

DELAY=${1:-5}

while true
do
  ACTIVE=$(find build*/.threads -name status -mmin -5 -printf "%T@ %p\n" | sort -n | awk 'END {print $NF}')
  if [ "${ACTIVE}" ]
  then
    clear
    cat ${ACTIVE}
    sleep ${DELAY}
  else
    echo -e "\nThere are no active builds available to view."
    exit 1
  fi
done
