#!/bin/bash

export ARCH=arm64
export CROSS_COMPILE=aarch64-linux-gnu-
export PATH=/opt/toolchains/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/:$PATH

if [ ! -d "linux" ]
then
  git clone --depth 1 https://github.com/hardkernel/linux.git -b odroidgoU-4.9.y
fi

cd linux
git pull

make odroidgou_defconfig
make -j$(expr $(expr $(nproc) \* 6) \/ 5)
