#!/bin/bash

export ARCH=arm64
export CROSS_COMPILE=aarch64-none-elf-
export PATH=/opt/toolchains/gcc-linaro-aarch64-none-elf-4.8-2013.11_linux/bin:/opt/toolchains/gcc-linaro-arm-none-eabi-4.8-2014.04_linux/bin:$PATH

if [ ! -d "u-boot" ]
then
  git clone https://github.com/JustEnoughLinuxOS/hardkernel-uboot.git -b odroidgoU-v2015.01
fi

cd u-boot
git pull
make odroidgou_defconfig
make
